### PR TITLE
Mention Java as out of the box supported language

### PR DESCRIPTION
**Pull request by honnix**
@EngHabu PTAL thanks.

### CODE REVIEW

**Review by EngHabu — APPROVED** [review]

**Comment by honnix** [comment]
Thanks for approving! Could you please help me merge it? It seems I don't have permission on this repo.

**Review by kumare3 — APPROVED** [review]

**Review by ArgentFalcon — APPROVED** [review]

**Comment by kanterov** [comment]
What about Scala. I think it's supported as well. API is designed specifically to have good UX when using Scala, and there are extensions specific for Scala.

**Comment by honnix** [comment]
This is complicated, unless we say `JVM based languages`, we will also miss something. But I'm OK adding Scala specifically.

**Comment by EngHabu** [comment]
Maybe we worded something like `JVM based languages (e.g. Java, Scala... etc.)` ?

**Comment by kumare3** [comment]
Not really all jvm languages right? As you can use the Java bridge but it may not be a native experience

**Comment by honnix** [comment]
Yeah I think it is  reasonable to just list Java and Scala as first class citizens of JVM family.

**Pull request merged**
